language: java
jdk:
- oraclejdk8
script: "./.ci/ci.sh"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: LSJ2yJUp8QuX7VRnapO3Ym6kfYxVhbFG1U2baWxPd0ncYBBleGEQt875kHiMgrFsrWRG1VNCphplae45MZ8ufLiKha9tN2vusdnYxEaYuj10OxA2ko0m3H4/HhQ2A53+fcAAWfOY6t6ngiP4jzOt0jPZHaLvvyiYOppHd8Fi5ek=
  - secure: CH8VfAXlNttLL/w8rZkdu2idvVkgZUBspYo+u5+NQLXw6JE9F4XPKWPI6caz7JMO81eWiMqvdKCeBXtVmHVpCWvZuGy0RXVZpqtgs5Yij4EKyVinfGjLDAk8+E0sR5lnINevzhsu9uV84a9K+0UN3knmUEMUTtorh1A68TX+Yi0=
  - secure: PfAJFIy14WBRlBR/+t83EHKxiyAWc13IYcNnjP0XD2XiZJmSq6ITqzDu3iwJTtRFEqjwQYhF8HYRQDBvnF5KRHLjK5IgbcBpj4mvppd2/vr2YSQ/LPffCoMOELGD5p/3IFLi9p0TXqXslj61Cq3dIvLnurlZW7qf4IuD85WJmy4=
  - secure: mqD94dv+lAjCj905Pmd2OYdGIqnUt9NiWJFG9Kjyoi7a965CNS2SvCk9uIE9+r14fe24vrHUpdyi8unpHYmuRBvkdoo4lB16+cfFziV8TnUle5f5xBGZSya+pnLQByXUEHgXnR2u+n5zuPrSRmsCbqZbFKooTFdcqsIE3K4veJQ=
  - secure: gGou1i+kg53gkJIHm761zmyhm4aoCV5IPeU77SCMl2KmdcnmF0XpsMtJUU16BQd3Lc6JwtnYTw79gA24377Z87Ylk4OLxN6pkkANzSJBGjdk3LNupfpkq18tNZZMW5Gs8gEZ36c86wNoqklN78rJseIp2v36cnnWStTAHw7UCZI=
  - secure: dTXO3Ei51PQ4id4X96poj1g+DkGnzyUAtVX/5AbTYr4/r3TrhX3GSHNsylB3Dq2/xDugMfrSUhgZc15ni3x1NF186G7C0QftjsqMeDLgSK+uOLkFVybqrl2YfWsPkhVIyuY1Fw5xkGs0HI8GMA/ReO0JRJfwAnrjokJa8Nyvrjw=
  - secure: pcESvJjUFWhZfbxCUojG7XIyA0chp3rIbWiKJtNjcE0QnjjtV9SRXH/VfpyaF1oXxAO/ohdr9tcNA4EmlkpNV10OAbDeqQGxfl4gt1UndNj6g1RuR6ISvtHoacSr9hyMu2UQFjTkl5BgPnGhLE5F5vBVhHYdaEktvw2dlgTxJK0=
