version: 2.1

jobs:
  test_8: 
    environment:
      GRADLE_OPTS: "-Dorg.gradle.workers.max=2"
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: gradlew test
          command: ./gradlew test

workflows:
  version: 2
  workflow:
    jobs:
    - test_8 